project:
  type: website
  output-dir: docs
  
website:
  title: "STA303 Course Guide"
  navbar:
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    css: styles.scss   # optional